induction c with d hd generalizing b,
intro ab_zero,
rw mul_zero at ab_zero,
have ab := eq_zero_or_eq_zero_of_mul_eq_zero a b ab_zero,
cases ab,
exfalso,
have hboom := ha ab,
exact hboom,
exact ab,
intro ab_aSd,
cases b,
rw mul_zero at ab_aSd,
symmetry at ab_aSd,
rw mul_eq_zero_iff at ab_aSd,
cases ab_aSd,
exfalso,
have hboom := ha ab_aSd,
exact hboom,
symmetry,
exact ab_aSd,
apply succ_eq_succ_of_eq,
repeat {rw mul_succ at ab_aSd},
rw add_right_cancel_iff at ab_aSd,
have hbd := hd b ab_aSd,
exact hbd,