intro h,
induction a with d hd,
cases h with c hc,
rw succ_eq_add_one at hc,
rw zero_add at hc,
rw add_comm at hc,
rw add_one_eq_succ at hc,
have hboom := zero_ne_succ c hc,
exact hboom,

have hSd_d := le_of_succ_le_succ (succ d) d h,
have hboom := hd hSd_d,
exact hboom,