cases hab with n hn,
cases hba with m hm,
rw hm at hn,
symmetry at hn,
rw add_assoc at hn,
have hmn := eq_zero_of_add_right_eq_self hn,
have hm_zero := add_right_eq_zero hmn,
rw hm,
rw hm_zero,
rw add_zero,
refl,